### PR TITLE
Remove default_value for required arguments

### PR DESCRIPTION
**Pull request by Amronos**
# 🦟 Bug fix

Removes `default_value` for `config_file` and `bridge_name` due to them being a required argument.
Changes `string` and `xml_string` to `world_string` in various places to maintain consistency, make clarification, and make fixes.
## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
Thanks for the patch!

Could you fix the conflicts?

**Review by caguero — CHANGES_REQUESTED** [review]
I also see `config_file` instances to be updated in:
 * ros_gz_bridge/launch/ros_gz_bridge.launch
 * ros_gz_bridge/launch/ros_gz_bridge.launch.py

**Comment by Amronos** [comment]
Changed `xml_string` to `string` in various places to maintain consistency and make fixes. Please review that too.

**Comment by caguero** [comment]
> Changed `xml_string` to `string` in various places to maintain consistency and make fixes. Please review that too.

Naming is hard but I thought `xml_string` was a lightly better name than `string`. Maybe `sdf_string` is better? I don't have a strong opinion here :) . Maybe `world_string`?

**Comment by Amronos** [comment]
I think now there are no more changes to be made. Can this merged?

**Review by caguero — APPROVED** [review]

**Pull request merged**
