### PR TITLE
Backport Some Changes from ros2 to jazzy

### LINKED ISSUE #589: Issue with ros2 jazzy and gazebo harmonic ros integration
Hello, I’m quite new wit ROS and gazebo and I have been having an issue for several days:
when following the tutorial : [Spawn a Gazebo model from ROS 2 — Gazebo harmonic documentation](https://gazebosim.org/docs/harmonic/ros2_spawn_model/)

It doesn’t work, after trying many time to reinstall, I found out that I don’t have the needed files in /opt/ros/jazzy/share/ros_gz_sim/launch

looking at the github it seems the jazzy/harmonic branch doesn’t have those files ( [ros_gz/ros_gz_sim/launch at jazzy · gazebosim/ros_gz · GitHub](https://github.com/gazebosim/ros_gz/tree/jazzy/ros_gz_sim/launch) )

What should I do to be able to make it work ?

thanks

### PR DESCRIPTION
**Pull request by Amronos**
# 🦟 Bug fix

Fixes #589 

## Summary
I have backported changes made in ros2 to jazzy which weren't already present in jazzy. Please tell me if anything is incorrect, or if the changes aren't supposed to be backported like this.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by azeey** [comment]
cc @caguero 

I think there are some fixes we need to make to the new launch actions before we backport https://github.com/gazebosim/ros_gz/issues/554

**Comment by ahcorde** [comment]
@azeey @caguero Can we use mergify to backport this feature ?

**Comment by Amronos** [comment]
Any updates on this?

**Comment by caguero** [comment]
> Any updates on this?

Let's do the backport after we merge #600 and #602.

**Comment by Amronos** [comment]
Should I make a new cleaner pull request and close this one?

**Comment by Amronos** [comment]
I am closing this pull request. I will make a new cleaner one later when everything happening right now with the ros2 branch gets a bit finalized.

**Pull request closed without merging**
