### PR TITLE
Shutdown explicitly while existing

### PR DESCRIPTION
**Pull request by evshary**
# 🦟 Bug fix

## Summary

Shutdown explicitly after creating an entity.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
Just checking, do we need to call `shutdown()` before the previous `return` calls as well?

**Comment by evshary** [comment]
> Just checking, do we need to call `shutdown()` before the previous `return` calls as well?

Good catch! I believe it should be.

**Review by Yadunund — APPROVED** [review]
Instead of multiple `rclcpp::shutdown()` calls, we could wrap this call inside a callback that will automatically execute once the program terminates  by relying on [rcpputils::make_scope_exit()](https://github.com/ros2/rcpputils/blob/35da074b1eb9ab94a869bc00dbae9922e2ed8c71/include/rcpputils/scope_exit.hpp#L58).

**Comment by azeey** [comment]
@evshary would you be able to apply @Yadunund's suggestion?

**Comment by evshary** [comment]
@Yadunund Thanks for your suggestion. I didn't know the tip before. :+1:

**Comment by evshary** [comment]
@azeey Do you have any clue why `Rpr__ros_gz__ubuntu_noble_amd64` is failing?
I'm not sure why it complains
```
13:49:54 Traceback (most recent call last):
13:49:54   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 21, in <module>
13:49:54     run_module('ros_buildfarm.scripts.devel.create_devel_task_generator', run_name='__main__')
13:49:54   File "<frozen runpy>", line 229, in run_module
13:49:54   File "<frozen runpy>", line 88, in _run_code
13:49:54   File "/tmp/ros_buildfarm/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 304, in <module>
13:49:54     sys.exit(main())
13:49:54              ^^^^^^
13:49:54   File "/tmp/ros_buildfarm/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 140, in main
13:49:54     get_binary_package_versions(apt_cache, debian_pkg_names))
13:49:54     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:49:54   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 180, in get_binary_package_versions
13:49:54     raise KeyError("No packages available for '%s'" % (debian_pkg_name,))
13:49:54 KeyError: "No packages available for 'ros-rolling-gz-sim-vendor'"
```

**Comment by azeey** [comment]
@ros-pull-request-builder retest this please

**Comment by azeey** [comment]
@evshary Yes, there was a regression in gz-common due to a change in gz-math. We've made a release of gz-common today, but it'll probably take a couple days for the change to propagate.

**Review by azeey — APPROVED** [review]

**Review by Yadunund — CHANGES_REQUESTED** [review]
Add `rcpputils` to `package.xml` as `<depend>`

**Comment by Yadunund** [comment]
> Add `rcpputils` to `package.xml` as `<depend>`

I hit send before finishing my comment 🤦🏼 

We should also include the appropriate header file and update CMakeLists.txt to explcitly link the target against `rcpputils`. I'm assuming this compiles right night through transitive linking against dependences `rclcpp` exports but it would be good to make this explicit.

**Comment by evshary** [comment]
Done. I've added the dependency and also header file / CMakefiles.txt

**Review by Yadunund — APPROVED** [review]
LGTM! Thanks for iterating!

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio update

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
