### PR TITLE
Refactor rgbd_camera_bridge demo

### PR DESCRIPTION
**Pull request by caguero**
Refactors the `rgbd_camera_bridge` demo leveraging the latest improvements in `ros_gz`. 

* I replaced the previous launch file from Python to XML.
* I didn't tackle the options using `ros_gz_image` or `ros_gz_point_cloud` for now.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by ahcorde — COMMENTED** [review]
similar comment https://github.com/gazebosim/ros_gz/pull/634

**Review by ahcorde — CHANGES_REQUESTED** [review]
similar comment https://github.com/gazebosim/ros_gz/pull/634

**Review by ahcorde — COMMENTED** [review]
Do you to add the Grid plugin to RViz?

**Comment by caguero** [comment]
> Do you to add the Grid plugin to RViz?

Is this plugin available for rolling?

**Comment by caguero** [comment]
> Do you to add the Grid plugin to RViz?

Loaded in [aebe372](https://github.com/gazebosim/ros_gz/pull/643/commits/aebe372ae595c384102e9fcc881b354b69ba1877).

**Comment by caguero** [comment]
> similar comment #634

This one is a bit tricker. The `rgbd_camera` sensor publishes on the ROS side:
```
- topic_name: "/rgbd_camera/image"
 ros_type_name: "sensor_msgs/msg/Image"
- topic_name: "/rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
- topic_name: "/rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
- topic_name: "/rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
```

All of these topics share the same `frame_id`, which is `rgbd_camera/link/rgbd_camera`. The problem is that the ROS/Gazebo coordinate convention is different for all these topics except for `/rgbd_camera/points`, which is correct.

The proper solution should be to republish `/rgbd_camera/image`, `/rgbd_camera/camera_info` and `/rgbd_camera/depth_image` with a different topic and also changing `frame_id`. We could then add a `static_transform_publisher` for the new `frame_id` with the transformation.

Alternatively, we could also try to resurrect #257 and combine it with some remappings similar to https://github.com/osrf/mbzirc/blob/main/mbzirc_ign/src/mbzirc_ign/model.py#L235-L260 (thanks @iche033 for the pointers).

I'd leave it for a separate PR.

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
