### PR TITLE
ROS version agnostic

### PR DESCRIPTION
**Pull request by chapulina**
This is the first step towards making the packages in this repository agnostic to the ROS version, so that we can more cleanly maintain both ROS 1 and ROS 2 integrations.

We're going to retire the recently created [ros2_ign](https://github.com/osrf/ros2_ign) repository and move that code to this repository. It hasn't been decided yet whether the code for ROS 1 and 2 will live in separate branches, or whether we want to split functionality into separate packages and put code specific to each ROS version into one of these smaller packages.

## Commits

* 2ebaa77 : Move files from `ros1_` directories to `ros_` without any changes
* d22e883 : Rename packages and fix tests
* a6f67bf : Rename functions, variables, namespaces, comments, etc.

## Migration plan

- [x] Add Debian renaming rules to ease transition of debian packages (CC @j-rivero )
- [x] Make pull request for SubT to use the new packages
- [x] Rename this repository

### CODE REVIEW

**Comment by chapulina** [comment]
I created 2 branches off of this one: `melodic` and `dashing`. We're going to proceed with ROS 2 development on the `dashing` branch.

Once we're ready, we'll start creating ROS 1 debs from the `melodic` branch and retire the `master` branch.

If there's a need to branch off for ROS 1 Noetic and/or ROS 2 Eloquent, new `ros1` / `ros2` branches will be created accordingly.

**Comment by j-rivero** [comment]
I think that I've ready the new packages in the prerelease repository. With the renaming the following scenarios are possible:

1. ros-melodic-ros-ign-* (new ones) packages are available as usual.
1. ros-melodic-ros1-ign-* (old ones) packages are available to install but they depen on the corresponding new package so both will be installed (the old one is an empty package).
1. if someone has installed ros-melodic-ros-ign* (old ones) then:
   1. apt-get upgrade: will not update packages (expected behavior of apt not installing packages that bring new deps).
   1. apt-get dist-upgrade will bring new ros-melodic-ros-ign packages to the system
   1. a single ros-melodic-ros-ign* or ros-melodic-ros1-ign-* installation will bring the new ones to the system.

**Comment by chapulina** [comment]
SubT PR: https://bitbucket.org/osrf/subt/pull-requests/291/

**Comment by chapulina** [comment]
Thanks, @j-rivero !
 
SubT shouldn't be updated until mid October, so we can't merge this into master or release into stable just yet. 

I'll keep this PR open for awareness. Until October, I will:

* Port updates to `master` to this branch
* Keep the `melodic` branch in sync with this branch
* Keep `dashing` in sync with this branch

We'll keep doing ROS 2 development on the `dashing` branch, and that won't be released anytime soon.

Once SubT can be updated, we can close this PR and the master branch, and start making ROS 1 stable releases from the `melodic` branch.

Let me know if I missed anything.

**Comment by chapulina** [comment]
* There's nothing on `master` which isn't on this branch yet: https://github.com/osrf/ros1_ign/compare/ros_ign...master
* PR updating `melodic` with this branch: https://github.com/osrf/ros1_ign/pull/46
* The only commit on this branch which is not on `dashing` isn't needed by ROS 2: https://github.com/osrf/ros1_ign/pull/47
* PR to update docs: https://bitbucket.org/ignitionrobotics/docs/pull-requests/35/

@j-rivero , I think we're ready to:

- [x] redirect all ROS 1 PRs to `melodic`
- [x] retire the `master` branch and make `melodic` the repository's default branch
- [ ] Make a `ros_ign` release from the `melodic` branch
- [x] Rename the repository to `ros_ign`
- [x] Announce the change on Gazebo Community
- [x] Close this PR

**Pull request closed without merging**
