### PR TITLE
Fix Deprecation Warning

### PR DESCRIPTION
**Pull request by DLu**
# 🦟 Bug fix

Fixes deprecation warning from [`image_transport/image_transport.h`](https://github.com/ros-perception/image_common/blob/a62ab876da2599627fe6a86bbc79040c62509422/image_transport/include/image_transport/image_transport.h#L41)

## Summary
Compiling on foxy led to this warning being printed:
```
In file included from /home/dlu/some_awesome_ws/src/ros_ign/ros_ign_image/src/image_bridge.cpp:18:
/opt/ros/foxy/include/image_transport/image_transport.h:41:89: note: #pragma message: Warning: This header is deprecated. Use 'image_transport.hpp' instead
   41 | #pragma message ("Warning: This header is deprecated. Use 'image_transport.hpp' instead")
      |                                                                                         ^

```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@DLu, Do you mind to rebase with `ros2`?  CI was fixed here https://github.com/ignitionrobotics/ros_ign/pull/159

**Comment by mjcarroll** [comment]
> @DLu, Do you mind to rebase with ros2? CI was fixed here #159

I got it

**Comment by DLu** [comment]
Thanks! Should I cherry pick to Foxy?

**Comment by mjcarroll** [comment]
> Thanks! Should I cherry pick to Foxy?

I believe that `foxy` is actually released off of `ros2`.  I'm not sure what the `foxy` branch is for, in this case.

https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml#L3509-L3530

**Comment by chapulina** [comment]
> I believe that foxy is actually released off of ros2. I'm not sure what the foxy branch is for, in this case.

See https://github.com/ignitionrobotics/ros_ign/issues/162#issuecomment-860796882

**Comment by DLu** [comment]
@chapulina So will someone else merge in the changes or should I cherry pick?

**Comment by chapulina** [comment]
Let me open some PRs to sync various branches.

**Pull request merged**
