### PR TITLE
[backport Humble] Added conversion for Detection3D and Detection3DArray (#523)

### PR DESCRIPTION
**Pull request by ahcorde**
# 🦟 Bug fix

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by iche033** [comment]
are the build failures expected?

**Comment by ahcorde** [comment]
@iche033 This is the `humble` branch not sure why this is compiling against `rolling` too

**Comment by iche033** [comment]
ok sounds like a separate CI setup issue.

**Review by iche033 — APPROVED** [review]

**Comment by ahcorde** [comment]
> ok sounds like a separate CI setup issue.

@iche033 https://github.com/gazebosim/ros_gz/pull/527

**Pull request merged**
