### PR TITLE
add std_msgs as dependency

### PR DESCRIPTION
**Pull request by ijnek**
Signed-off-by: Kenji Brameld <kenjibrameld@gmail.com>

# 🦟 Bug fix

## Bug

ROS2 Rolling on Ubuntu Jammy fails to build due to missing dependency on ``std_msgs``.

```
ros_ign_ws $colcon build --packages-select ros_ign_gazebo
Starting >>> ros_ign_gazebo
--- stderr: ros_ign_gazebo                             
/home/ijnek/workspaces_ros2/ros_ign_ws/src/ros_ign/ros_ign_gazebo/src/create.cpp:25:10: fatal error: std_msgs/msg/string.hpp: No such file or directory
   25 | #include <std_msgs/msg/string.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/create.dir/build.make:76: CMakeFiles/create.dir/src/create.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/create.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< ros_ign_gazebo [2.55s, exited with code 2]

Summary: 0 packages finished [2.75s]
  1 package failed: ros_ign_gazebo
  1 package had stderr output: ros_ign_gazebo
```

## Summary

Adds dependency to ``package.xml`` and ``CMakeLists.txt``.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Review by adityapande-1995 — COMMENTED** [review]
@ahcorde should we also declare ``ignition-transport`` and ``ignition-msgs`` as explicit dependencies ? Used here : https://github.com/ignitionrobotics/ros_ign/blob/c7f74b75ed37cdb90b76df5821b575f2b9a225ad/ros_ign_gazebo/src/create.cpp#L17-L19

**Comment by ahcorde** [comment]
> @ahcorde should we also declare `ignition-transport` and `ignition-msgs` as explicit dependencies ? Used here :
> 
> https://github.com/ignitionrobotics/ros_ign/blob/c7f74b75ed37cdb90b76df5821b575f2b9a225ad/ros_ign_gazebo/src/create.cpp#L17-L19

If this is used of course we have to.

@ijnek do you mind to add then ?

**Review by chapulina — APPROVED** [review]
Thanks! I believe this closes #220. We may need to backport it to `foxy` and `galactic`

**Comment by ahcorde** [comment]
@chapulina CI is still red because of the Jammy packages, should we wait to get a green CI ?

**Comment by ahcorde** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
`ros_ign_gazebo` built fine on the ROS farm, which is all we need to verify that this PR works. Merging to unblock follow up PRs.

**Pull request merged**
