### PR TITLE
Add a way to pass extra parameters to ros_gz_bridge

### LINKED ISSUE #624: Passing parameters to `ros_gz_bridge` from launch files
## Desired behavior
It would be nice to have a way to pass `qos_overrides` or other parameters to `ros_gz_bridge` with the launch files `ros_gz_sim.launch.py`, `ros_gz_spawn_model.py`, and `ros_gz_bridge.launch.py`, etc. which I don't think is currently possible.

## Alternatives considered
--

## Implementation suggestion
There could be another argument added to the launch files, something like `bridge_params` which can later be substituted into the `parameters` of the `ros_gz_bridge` node.

I am willing to work on this, but first wanted to open an issue to discuss how this should be done.

### PR DESCRIPTION
**Pull request by Amronos**
# 🎉 New feature

Closes #624

## Summary
Added a new argument `bridge_params` to allow users to pass extra parameters to `ros_gz_bridge` when using the launch file. An example of these parameters would be `qos_overrides`
I have changed the node declarations to an opaque function so that I can get the value of `bridge_params`.
`bridge_params` is converted from string to dictionary and then passed to the parameters of the `ros_gz_bridge` node.
The way I have done all of this is complicated and so please do tell me if there is an easier way to do this.

## Test it
To test this something like the following command can be used:
```ros2 launch ros_gz_bridge ros_gz_bridge.launch.py bridge_name:=ros_gz_bridge config_file:=<path_to_your_YAML_file> bridge_params:="'qos_overrides./topic_name.publisher.durability': 'transient_local', 'qos_overrides./another_topic_name.publisher.durability': 'transient_local'"```

Then to check if the qos overrides have applied:
```ros2 topic info /topic_name --verbose```
```ros2 topic info /another_topic_name --verbose```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by caguero — CHANGES_REQUESTED** [review]
There are some style errors. See https://github.com/gazebosim/ros_gz/actions/runs/11588839442/job/32263218643?pr=628

**Comment by azeey** [comment]
I haven't had time to dig into this, but it feels like a big code change for a fairly small feature. Is it the conversion from string to dictionary that requires the use of the opaque function? Another approach I would consider is moving more of the logic into the gz_server Action or even reverting the current architecture where the [Action](https://github.com/gazebosim/ros_gz/blob/jazzy/ros_gz_bridge/ros_gz_bridge/actions/ros_gz_bridge.py) includes a launch file
https://github.com/gazebosim/ros_gz/blob/2658f27fbea5dd14af2c47ac787071b4772c2757/ros_gz_bridge/ros_gz_bridge/actions/ros_gz_bridge.py#L146-L150

and instead have the `ros_gz_bridge.launch.py` file use the [Action](https://github.com/gazebosim/ros_gz/blob/jazzy/ros_gz_bridge/ros_gz_bridge/actions/ros_gz_bridge.py). It seems like we have more flexibility there.

**Comment by Amronos** [comment]
> Is it the conversion from string to dictionary that requires the use of the opaque function?

Yes.

>or even reverting the current architecture where the [Action](https://github.com/gazebosim/ros_gz/blob/jazzy/ros_gz_bridge/ros_gz_bridge/actions/ros_gz_bridge.py) includes a launch file and instead have the `ros_gz_bridge.launch.py` file use the [Action](https://github.com/gazebosim/ros_gz/blob/jazzy/ros_gz_bridge/ros_gz_bridge/actions/ros_gz_bridge.py). It seems like we have more flexibility there.

That does sound like a good idea.

**Comment by Amronos** [comment]
Any updates on this PR?

**Review by caguero — COMMENTED** [review]
Could you merge from `ros2`. In particular, I want to make sure that this patch is consider in your refactor:

https://github.com/gazebosim/ros_gz/pull/620/files

**Review by caguero — COMMENTED** [review]
Does this test work for you? (remember to update the path to the bridge config file).

```
ros2 launch ros_gz_sim ros_gz_sim.launch bridge_name:=ros_gz_bridge config_file:=/home/caguero/ros_gz_ws/src/ros_gz/ros_gz_bridge/test/config/full.yaml world_sdf_file:=empty.sdf use_composition:=True create_own_container:=True
```

**Comment by Amronos** [comment]
> Does this test work for you? (remember to update the path to the bridge config file).
> 
> ```
> ros2 launch ros_gz_sim ros_gz_sim.launch bridge_name:=ros_gz_bridge config_file:=/home/caguero/ros_gz_ws/src/ros_gz/ros_gz_bridge/test/config/full.yaml world_sdf_file:=empty.sdf use_composition:=True create_own_container:=True
> ```

I haven't specifically run this command, but I have used the `ros_gz_sim.launch.py` launch file inside another python launch file with composition enabled.

**Comment by caguero** [comment]
> > Does this test work for you? (remember to update the path to the bridge config file).
> > ```
> > ros2 launch ros_gz_sim ros_gz_sim.launch bridge_name:=ros_gz_bridge config_file:=/home/caguero/ros_gz_ws/src/ros_gz/ros_gz_bridge/test/config/full.yaml world_sdf_file:=empty.sdf use_composition:=True create_own_container:=True
> > ```
> 
> I haven't specifically run this command, but I have used the `ros_gz_sim.launch.py` launch file inside another python launch file with composition enabled.

I'm getting an error that I don't get with the `ros2` branch:
```
[INFO] [launch]: All log files can be found below /home/caguero/.ros/log/2024-11-14-17-40-26-288785-cold-1915140
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): 'str' object has no attribute 'perform'
```

**Comment by Amronos** [comment]
The XML launch file should work now.
Should I add the `bridge_params` argument to the other launch files?

**Comment by caguero** [comment]
> The XML launch file should work now. Should I add the `bridge_params` argument to the other launch files?

That'd be great!

**Comment by Amronos** [comment]
Should be ready to merge now!

**Review by caguero — COMMENTED** [review]
I think there's still something not working for me. If I run:
```
ros2 launch ros_gz_sim ros_gz_sim.launch.py bridge_name:=ros_gz_bridge config_file:=/home/caguero/ros_gz_ws/src/ros_gz/ros_gz_bridge/test/config/full.yaml world_sdf_file:=empty.sdf use_composition:=True create_own_container:=True
```

And then:
```
caguero@cold:~/ros_gz_ws$ ros2 node list
WARNING: Be aware that there are nodes in the graph that share an exact name, which can have unintended side effects.
/gz_server
/gzserver
/gzserver
/gzserver
/launch_ros_2128322
/ros_gz_bridge
/ros_gz_bridge
/ros_gz_container
```

It shows multiple instances of the bridge and `gzserver`. This issue was fixed in https://github.com/gazebosim/ros_gz/pull/620 but it's resurfacing here.

**Comment by caguero** [comment]
@Amronos , out of curiosity, were you able to solve the latest issue (duplicated nodes)?

**Comment by Amronos** [comment]
> @Amronos , out of curiosity, were you able to solve the latest issue (duplicated nodes)?

Yes, it was fixed in commit f2d6cda. The PR should be ready to merge.

**Review by caguero — APPROVED** [review]
All looks good to me now, thanks!

**Comment by Amronos** [comment]
@caguero Can this also be backported to Jazzy? If yes, #629 should be backported first.

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
