### PR TITLE
Add option to change material color from ROS.

### PR DESCRIPTION
**Pull request by bperseghetti**
Forward port of PR #486 from humble to iron

    * Message and bridge for MaterialColor.

    This allows bridging MaterialColor from ROS to GZ and is
    important for allowing simulation users to create status lights.

# ➡️ Forward port

Single feature forward port from modified cherry-pick

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by azeey** [comment]
@bperseghetti can you merge from `ros2` to get updated CI checks?

**Comment by bperseghetti** [comment]
@azeey back to you! 🙃

**Review by azeey — APPROVED** [review]
LGTM!

**Comment by azeey** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
