### PR TITLE
Add missing rosidl_cmake dep to ros_gz_bridge

### PR DESCRIPTION
**Pull request by Yadunund**
Address https://build.ros2.org/job/Ibin_ujv8_uJv8__ros_gz_bridge__ubuntu_jammy_arm64__binary/1/

### CODE REVIEW

**Comment by ahcorde** [comment]
@Yadunund Is this a new package on Iron ? or is this package already released on Humble ?

**Review by clalancette — DISMISSED** [review]
Though this would likely resolve the build warning, this isn't quite right for `iron`.

Instead, what should happen here is that this package should take a dependency on `rosidl_pycommon`, and the code in https://github.com/gazebosim/ros_gz/blob/e84dda62a8b066f3d218920ca70d6623f08c2b05/ros_gz_bridge/ros_gz_bridge/__init__.py#L21 should be updated to be `from rosidl_pycommon import expand_template`.

To answers @ahcorde's question; this deprecation is new in `iron`, so this should only be released into `rolling` and `iron`.

**Comment by clalancette** [comment]
I just pushed 158bd3b, which I think is the proper fix here.

**Comment by ahcorde** [comment]
CI fixed here https://github.com/gazebosim/ros_gz/pull/395

**Review by ahcorde — APPROVED** [review]

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
