### PR TITLE
Add a virtual destructor to suppress compiler warning

### PR DESCRIPTION
**Pull request by mjcarroll**

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
are you going to backport this?

**Comment by mjcarroll** [comment]
@mergifyio backport humble iron

**Comment by mjcarroll** [comment]
@ahcorde did I do this incorrectly?

**Comment by ahcorde** [comment]
no mergify in this repository, I don't have right to enable it

**Comment by ahcorde** [comment]
backports:
 - https://github.com/gazebosim/ros_gz/pull/505
 - https://github.com/gazebosim/ros_gz/pull/504

**Pull request merged**
