### PR TITLE
Backport Some Changes from ros2 to jazzy

### LINKED ISSUE #589: Issue with ros2 jazzy and gazebo harmonic ros integration
Hello, I’m quite new wit ROS and gazebo and I have been having an issue for several days:
when following the tutorial : [Spawn a Gazebo model from ROS 2 — Gazebo harmonic documentation](https://gazebosim.org/docs/harmonic/ros2_spawn_model/)

It doesn’t work, after trying many time to reinstall, I found out that I don’t have the needed files in /opt/ros/jazzy/share/ros_gz_sim/launch

looking at the github it seems the jazzy/harmonic branch doesn’t have those files ( [ros_gz/ros_gz_sim/launch at jazzy · gazebosim/ros_gz · GitHub](https://github.com/gazebosim/ros_gz/tree/jazzy/ros_gz_sim/launch) )

What should I do to be able to make it work ?

thanks

### PR DESCRIPTION
**Pull request by Amronos**
# 🦟 Bug fix
A cleaner version of #599.

Fixes #589.

## Summary
I have backported changes made in ros2 to jazzy. Changelogs and version numbers have not been backported.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by Amronos** [comment]
@ahcorde can this be merged?

**Comment by caguero** [comment]
> @ahcorde can this be merged?

Thanks @Amronos ! While I'm testing it, could you fix DCO please?

**Comment by Amronos** [comment]
~Looks like I messed up during the rebase, I am sorry! I am trying to revert this.~ Reverted.

**Comment by Amronos** [comment]
I am trying to change the signoff message for commit [dbd127a](https://github.com/gazebosim/ros_gz/pull/607/commits/dbd127a4f2a8de9f87fcc2b988d059c206818b40), but I am facing difficulties in doing that (I have never done things like these before), can you help me? @caguero

**Comment by Amronos** [comment]
Does the rebase I did just now look ok and is the DCO also fixed now? The changelogs and version numbers got a bit messed up, I will commit a bit later to fix that.

**Comment by caguero** [comment]
> Does the rebase I did just now look ok and is the DCO also fixed now? The changelogs and version numbers got a bit messed up, I will commit a bit later to fix that.

I still see DCO not passing. Are you following https://github.com/gazebosim/ros_gz/pull/607/checks?check_run_id=30308693405?

**Comment by Amronos** [comment]
> Are you following https://github.com/gazebosim/ros_gz/pull/607/checks?check_run_id=30308693405?

Yes, I am not the author of the commits that are causing DCO to fail, and so I don't think I am supposed to run a full sign-off using `git rebase HEAD~33 --sign-off`.

**Review by caguero — APPROVED** [review]

**Pull request merged**
