### PR TITLE
Support fortress with melodic

### PR DESCRIPTION
**Pull request by nkoenig**
Signed-off-by: Nate Koenig <nate@openrobotics.org>

# 🎉 New feature

## Summary

Adds support for Ignition Fortress with ROS Melodic.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by chapulina — CHANGES_REQUESTED** [review]
This is changing the default to Fortress. Last time we changed the Melodic default from Blueprint to Dome we broke downstream users, see https://github.com/ignitionrobotics/ros_ign/issues/130. What's the migration strategy this time?

Also, could you add Fortress to Travis CI, and a row to the README?

**Comment by nkoenig** [comment]
> This is changing the default to Fortress. Last time we changed the Melodic default from Blueprint to Dome we broke downstream users, see #130. What's the migration strategy this time?

I've updated this PR to default to Dome, and only use Fortress if you manually set IGNITION_VERSION=fortress. Does that resolve this issue?

> 
> Also, could you add Fortress to Travis CI, and a row to the README?
I've updated the readme. Can you point me to instructions about updating Travis?

**Comment by chapulina** [comment]
> I've updated this PR to default to Dome, and only use Fortress if you manually set IGNITION_VERSION=fortress. Does that resolve this issue?

Yes, thanks!

> Can you point me to instructions about updating Travis?

Ah sorry, when I say Travis, I mean GitHub actions. It should go here:

https://github.com/ignitionrobotics/ros_ign/blob/3af3d38ada0e479313a433e24b0538581a6caaa1/.github/workflows/build-and-test.sh#L12-L20

and here:

https://github.com/ignitionrobotics/ros_ign/blob/3af3d38ada0e479313a433e24b0538581a6caaa1/.github/workflows/melodic-ci.yml#L12-L17

**Comment by chapulina** [comment]
Fortress CI is going to fail for now unless we add the pre-release repo

**Review by chapulina — APPROVED** [review]
Pushed some more changes in dc59941a1786aaf9f7cc4d7f2b7f340d1e445065, LGTM with happy CI

**Pull request merged**
