### PR TITLE
Change ubuntu 20.04 to 22.04

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🦟 Bug fix

## Summary

`Rolling` should use `Ubuntu Jammy`

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Comment by ahcorde** [comment]
@mjcarroll there are some packages that are not released properly

```bash
apt: command [apt-get install -y ros-rolling-image-transport-plugins] failed
```

**Comment by nuclearsandwich** [comment]
> ```shell
> apt: command [apt-get install -y ros-rolling-image-transport-plugins] failed
> ```

If the package were not released then there would be an error earlier in the process during the bloom stage. This error indicates that although the package is released, it's not available in the target repository.
Looking at the build output, this action is using the ROS 2 main repository rather than the [ROS 2 testing](http://docs.ros.org/en/rolling/Installation/Testing.html) repository which is the repository used by "native" ROS devel and PR jobs on the ROS build farm.

[The repository status page](
http://repo.ros2.org/status_page/ros_rolling_default.html?q=image_transport_plugins) currently shows that image_transport_plugins has not yet been sync'd to the main repository but it is in testing.
I've taken a screenshot since this status page will update soon and will look different:
status_page showing image_transport_plugins

There is a pending [Rolling sync](https://discourse.ros.org/t/preparing-for-rolling-sync-2022-04-20/25167) which will bring this package to main, but for CI jobs we recommend targeting the testing repository since this represents what's upcoming in the next sync.

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by ahcorde** [comment]
@chapulina and/or @nuclearsandwich  This PR is required https://github.com/ignitionrobotics/ros_ign/pull/242

**Comment by chapulina** [comment]
"just" a few test failures 🎉

**Pull request merged**
