### PR TITLE
[foxy] Edifice support

### PR DESCRIPTION
**Pull request by chapulina**
# 🎉 New feature

## Summary

Support the upcoming Ignition release.

## Test it

1. Install Edifice nightlies: https://ignitionrobotics.org/docs/edifice/install_ubuntu
1. Set the env var: `export IGNITION_VERSION=edifice`
1. Compile against Foxy

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] ~~Updated migration guide (as needed)~~
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]
There are some updates about noetic, which are not part of this PR (I believe)

**Review by ahcorde — CHANGES_REQUESTED** [review]
```
4: Test command: /usr/bin/python3 "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/root/ws/build/ros_ign_image/test_results/ros_ign_image/lint_cmake.xunit.xml" "--package-name" "ros_ign_image" "--output-file" "/root/ws/build/ros_ign_image/ament_lint_cmake/lint_cmake.txt" "--command" "/opt/ros/foxy/bin/ament_lint_cmake" "--xunit-file" "/root/ws/build/ros_ign_image/test_results/ros_ign_image/lint_cmake.xunit.xml"
4: Test timeout computed to be: 60
4: -- run_test.py: invoking following command in '/code/ros_ign_image':
4:  - /opt/ros/foxy/bin/ament_lint_cmake --xunit-file /root/ws/build/ros_ign_image/test_results/ros_ign_image/lint_cmake.xunit.xml
4: CMakeLists.txt:20: Extra spaces between 'if' and its () [whitespace/extra]
4: CMakeLists.txt:29: Extra spaces between 'elseif' and its () [whitespace/extra]
```

**Comment by chapulina** [comment]
CI should be fixed by 9a6b745

**Review by ahcorde — CHANGES_REQUESTED** [review]
the `lint_cmake` is still there https://travis-ci.org/github/ignitionrobotics/ros_ign/jobs/763301487

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
